# Generated by Django 5.1.8 on 2025-04-18 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailVerification',
            new_name='EmailVerificationEvent',
        ),
    ]
