# Generated by Django 5.1.8 on 2025-04-22 20:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_email_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationevent',
            name='token',
            field=models.UUIDField(default=uuid.uuid1),
        ),
    ]
